// Regenerates web/buildStamp.ts with the current time before each build, so the UI can show when
// the deployed bundle was built.
const fs = require("fs");
const path = require("path");

const stamp = Date.now();
const out = path.join(__dirname, "..", "web", "buildStamp.ts");
fs.writeFileSync(out, `// Generated by scripts/writeBuildStamp.js on each build. Do not edit.\nexport const buildStamp = ${stamp};\n`);
console.log("build stamp:", stamp, new Date(stamp).toISOString());
